config:
  easyMode: true
  level: 1
  updatesPerSecond: 240
  fps: 60
  currentTheme: Default
  forceBackgroundColor: true
  storeDelayMs: 500
  softDropDelayMs: 20
  softDropGravityMsPerRow: 20
  comboDelayMs: 6000
  debug: false
  themes:
    - name: Default
      mainColorsGradient:
        - "#4cd137"
        - "#4cce3c"
        - "#4ccb41"
        - "#4cc54a"
        - "#4bb85d"
        - "#4bab70"
        - "#42916a"
        - "#387763"
        - "#254f42"
      gameOverColorsGradient:
        - "#e84118"
        - "#d63c1f"
        - "#c43725"
        - "#a02d32"
        - "#57194b"
      mainColor: "#3a9e83"
      gameOverColor: "#e84118"
      backgroundColor: "#141a14"
      foregroundColor: "#dfdfdf"
      valueColor: "#4bb365"
      trueColor: "#4cd137"
      falseColor: "#e84118"
      IColor: "#00a8ff"
      OColor: "#fbc531"
      TColor: "#9c88ff"
      JColor: "#2b2cd5"
      LColor: "#f28325"
      SColor: "#4cd137"
      ZColor: "#e84118"
    - name: Deep Dark
      mainColorsGradient:
        - "#2985b3"
        - "#2c82b0"
        - "#2f7fb1"
        - "#3776a9"
        - "#3e609a"
        - "#3e4a8d"
        - "#383a7a"
        - "#372f65"
        - "#241f42"
      gameOverColorsGradient:
        - "#584ca1"
        - "#803f91"
        - "#a83180"
      mainColor: "#3776a9"
      gameOverColor: "#a83180"
      backgroundColor: "#08061a"
      foregroundColor: "#dfdfdf"
      valueColor: "#1787e8"
      trueColor: "#2985b3"
      falseColor: "#a83180"
      IColor: "#9dd9d2"
      OColor: "#79bcb8"
      TColor: "#5ec2b7"
      JColor: "#2ca6a4"
      LColor: "#3aa7a3"
      SColor: "#5786b0"
      ZColor: "#625cb5"
    - name: Autumn Haze
      mainColorsGradient:
        - "#e07a5f"
        - "#e9a377"
        - "#f2cc8f"
        - "#d6c692"
        - "#babf95"
        - "#9eb988"
        - "#81b29a"
      gameOverColorsGradient:
        - "#f4a08b"
        - "#ee9c8b"
        - "#e9968b"
        - "#dd888c"
        - "#d265bc"
      mainColor: "#f2cc8f"
      gameOverColor: "#d265bc"
      backgroundColor: "#201813"
      foregroundColor: "#dfdfdf"
      valueColor: "#f2cc8f"
      trueColor: "#8cf28c"
      falseColor: "#f28c8c"
      IColor: "#80d4ff"
      OColor: "#ffe369"
      TColor: "#cec4ff"
      JColor: "#8080ff"
      LColor: "#ffc28c"
      SColor: "#95ff85"
      ZColor: "#ff9980"
    - name: Blood moon
      mainColorsGradient:
        - "#c52233"
        - "#a51c30"
        - "#a7333f"
        - "#74121d"
        - "#580c1f"
      gameOverColorsGradient:
        - "#e84118"
        - "#d63c1f"
        - "#c43725"
        - "#a02d32"
        - "#57194b"
      mainColor: "#d81159"
      gameOverColor: "#57194b"
      backgroundColor: "#1a0a0a"
      foregroundColor: "#dfdfdf"
      valueColor: "#d81159"
      trueColor: "#ffae03"
      falseColor: "#e84118"
      IColor: "#e67f0d"
      OColor: "#ffae03"
      TColor: "#fe4e00"
      JColor: "#e9190f"
      LColor: "#8f2d56"
      SColor: "#ed4139"
      ZColor: "#d81159"
controls:
  moveLeft: a
  moveRight: d
  rotateLeft: ","
  rotateRight: .
  swapHold: z
  softDrop: s
  hardDrop: " "
  forfeit: t
  retry: r